module.exports = async function(client, message, cmd, args, prefix) {

message.channel.send('Console cleared.:white_check_mark:').then(m => {
  m.delete(3000);
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
     console.log(` `)
})
}